// <auto-generated />
namespace MVC_CodeFirst_2_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class MoviesDbCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoviesDbCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202606030509249_MoviesDb Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
